### ISSUE TITLE
Parent issue to all projects: Add Start Career in Foss banner

### ISSUE THREAD

**Issue by aassoiants** [bitcoin-dev-project/bitcoin-dev-project#27]
- [ ] In terms of design, i propose having the announcement content centralized of at least left-aligned to where the website content itself starts. For instance, the following design (yes, while being temporary), doesn't draw my eyes
![image](https://github.com/bitcoin-dev-project/bitcoin-dev-project/assets/126297088/48be3177-3c2b-45c4-8e93-bb36bf58fa88)

- [ ] In terms of CTA, I propose mimicking what ClickUp does, by creating an obvious button as an interaction - not the text. Image to show what i mean. And a few other [ideas here](https://userguiding.com/blog/website-notification-banner/). 
![image](https://github.com/bitcoin-dev-project/bitcoin-dev-project/assets/126297088/e88b3d7e-b51a-42d4-b0cb-10150bff8544)

- [ ] Waiting for final copy from @adamjonas. My proposal: 
"Start your career in bitcoin FOSS. 
A no-cost program for devs interested in working full-time in bitcoin or lightning FOSS.
CTA: Start Application Now"

- [ ] Add listener to umami tracker

- [ ] Remove Dec 31. 2023

**Comment by kouloumos** [comment]
Utilizing a banner across all projects is an effective means of public outreach, especially when communicating about potential opportunities or product launches. With this in mind, exploring a mechanism to uniformly distribute banner notifications across all projects could prove advantageous.

This could potentially be achieved by having all projects access notifications from a single endpoint, streamlining the process and ensuring consistency.
